### ISSUE TITLE
Error message output obscures network info on setups with limited console logging

### ISSUE THREAD

**Issue by PeterDavidCarter** [theKrazyCoder/pwnet#2]
E.g. if you're trying to use this on a Fedora server with the relatively short max scroll limit and there are multiple timeouts while creating sockets you won't be able to find the banner info. See pull request for provisional fix. Best would be for user to specify value via command line.

**Comment by theKrazyCoder** [comment]
I approved the pull request.... Maybe I should add you as a contributor

**Comment by PeterDavidCarter** [comment]
Sure, I'm more than happy to contribute bits and pieces when I get the time. I'm working on some packet sniffing which I'm more than happy to merge as part of this account. This information should be open and available so the internet can return to the people.
